### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by Chexian1** [xenv/S-mall-ssm#12]
楼主你好，我打开项目发现类很多，但是运行后发现功能并不是那么多，这是一个完整的天猫商城么想问？是不是只要加入数据，填充404跳转后的页面，这就是一个完整的商城呢？

**Comment by Chexian1** [comment]
还有我要添加商品只能从数据库添加么，似乎没有给admin一个后台管理系统

**Comment by xenv** [comment]
有全套的，请您认真阅读一下README



---原始邮件---
发件人: "Chexian1"<notifications@github.com&gt;
发送时间: 2019年10月9日(星期三) 晚上11:53
收件人: "xenv/S-mall-ssm"<S-mall-ssm@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [xenv/S-mall-ssm] 一些疑问 (#12)



还有我要添加商品只能从数据库添加么，似乎没有给admin一个后台管理系统

**Comment by xenv** [comment]
您在 README 的 demo 体验之后再调试本地程序。404是因为配置问题。网站必须在根目录下。



---原始邮件---
发件人: "Chexian1"<notifications@github.com&gt;
发送时间: 2019年10月9日(星期三) 晚上7:42
收件人: "xenv/S-mall-ssm"<S-mall-ssm@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [xenv/S-mall-ssm] 一些疑问 (#12)


  楼主你好，我打开项目发现类很多，但是运行后发现功能并不是那么多，这是一个完整的天猫商城么想问？是不是只要加入数据，填充404跳转后的页面，这就是一个完整的商城呢？
