### ISSUE TITLE
没有商品展示

### ISSUE THREAD

**Issue by Chexian1** [xenv/S-mall-ssm#13]
![截图1571062426](https://user-images.githubusercontent.com/50158987/66758053-184fc500-eed0-11e9-96f4-375cbaa8cb67.png)
我连接了数据库运行项目后为什么没有商品展示出来，想问，搜索栏也搜索不了

**Comment by xenv** [comment]
测试数据库没有商品数据，请到后台添加分类后，自行添加商品。
