### ISSUE TITLE
加入购物车后, 增加数量, 统一结算时计算结果出错

### ISSUE THREAD

**Issue by h920553245** [xenv/S-mall-ssm#16]
操作:
    1. 商品添加购物车
    2. 在购物车内,增加商品数量
    3. 点击结算, 金额与数量不一致

**Comment by xenv** [comment]
小bug欢迎提PR，应该是哪里的数return错了



---原始邮件---
发件人: "二瓜"<notifications@github.com&gt;
发送时间: 2020年2月3日(周一) 晚上10:51
收件人: "xenv/S-mall-ssm"<S-mall-ssm@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [xenv/S-mall-ssm] 加入购物车后, 增加数量, 统一结算时计算结果出错 (#16)



操作:
 1. 商品添加购物车
 2. 在购物车内,增加商品数量
 3. 点击结算, 金额与数量不一致

**Comment by xenv** [comment]
#17 谢谢
