### ISSUE TITLE
不全选购物车中商品进行结算时，确认订单信息界面显示异常

### ISSUE THREAD

**Issue by purpleflowerssssss** [xenv/S-mall-ssm#18]
1.全选购物车商品进行结算，确认订单信息时没有任何问题。
2.选择购物车中部分商品时，购物车界面信息没有问题。进行结算时，确认订单界面信息有问题，确认订单中所显示的商品是购物车中所有商品，包括选择的和未选择的。
       看了部分源码，感觉是购物车界面遍历了cartitem表中deleteAt为null的字段，确认订单界面也遍历了cartitem表中deleteAt为null的字段，所以确认订单界面中的商品信息并不是购物车中被选择的商品信息。菜鸟一枚，如有不对之处，请见谅，同时急求解决方法。

**Comment by xenv** [comment]
感谢你的反馈，最近无维护计划，可以自行排查原因，欢迎提交 PR。
