### ISSUE TITLE
权限为superAdmin和user的用户提交订单后都能自己发货，user越权了吧

### ISSUE THREAD

**Issue by purpleflowerssssss** [xenv/S-mall-ssm#19]

**Comment by xenv** [comment]
是为了方便测试用户体验发货后流程，无需切换两个账号。



---原始邮件---
发件人: "purpleflowerssssss"<notifications@github.com&gt;
发送时间: 2020年5月1日(周五) 上午10:44
收件人: "xenv/S-mall-ssm"<S-mall-ssm@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [xenv/S-mall-ssm] 权限为superAdmin和user的用户提交订单后都能自己发货，user越权了吧 (#19)
