### ISSUE TITLE
乱码问题以及分类图片的问题

### ISSUE THREAD

**Issue by 793404933** [xenv/S-mall-ssm#2]
（1）后台添加属性，中文乱码【后台添加分类时中文不乱码】请问一下，是为什么~
（2）分类管理读取图片不出来，是少了一个数据库表来存储图片信息嘛？也没找到分类图片存放目录pictures/category/,能不能问一下~

**Comment by xenv** [comment]
第一个问题，我也不太清楚，你可以在本地 Debug 看看，是在插入数据库之前乱码还是插入数据库之后才乱码，然后再看一下属性表的编码格式。
第二个问题，分类图片，是没有这个表，我直接和分类的 id 绑定了，你传了图片会放到 pictures/category/id.jpg ，如果没放到，文件夹如果没有会被程序创建，可以看一下是不是文件夹权限的问题

**Comment by 793404933** [comment]
好的，谢谢你了，我再想问一下pictures/category这个文件夹具体在工程的哪个目录下~，还是没有找到，但是图片现在可以正常显示了。

**Comment by xenv** [comment]
图片目录在tomcat的那个网站文件夹里面（一般是ROOT文件夹），如果是idea里面运行，会放在target文件夹里面，具体位置你可以自己找一下，这个设计不太好，不过安装比较方便

**Comment by Chexian1** [comment]
我仔细看了一下不理解 为什么对应每个pojo类都有一个pojoExtension类，它的作用是什么，求教。

**Comment by xenv** [comment]
> 我仔细看了一下不理解 为什么对应每个pojo类都有一个pojoExtension类，它的作用是什么，求教。

https://www.yuque.com/page/luan.ma/mybatis-generator-insulate

**Comment by Chexian1** [comment]
好多数据表的字段都看不太明白代表什么含义，要是各个数据表的字段有介绍就更好了

**Comment by Chexian1** [comment]
比如Property表和propertyValue表对应的实体是什么意思，在这个项目中。

**Comment by Chexian1** [comment]
还有这个ManytoOne等注解为什么大括号内没有内容也可以产生作用呢？

**Comment by Chexian1** [comment]
求教，谢谢！
