### ISSUE TITLE
求教：超链接传值

### ISSUE THREAD

**Issue by purpleflowerssssss** [xenv/S-mall-ssm#21]
<a href="?keyword=${keyword}&sort=comment" class="${param.sort=='comment'?'selected':''}">人气</a>
求教：代码中href属性问号前为空，请问点击“人气”把keyword和sort传给了谁?怎么实现的？我个人以为是传给了当前页面，可把参数传给当前页面不能进行处理，这并不能实现排序。
搜索后排序地址栏是：search?keyword=红富士&sort=comment
分类后排序地址栏是：category?id=12&sort=comment

**Comment by xenv** [comment]
不太明白你问的问题，sort=comment 代码侧会改变结果的顺序，怎么实现的我已经忘了
