### ISSUE TITLE
IDEA导入工程运行报错

### ISSUE THREAD

**Issue by HaoYue12** [xenv/S-mall-ssm#4]
本人用IDEA导入该项目，用的是tomcat 9。导入后运行前台首页出来，可是除了轮播图片和头部底部显示， 其他都没出来，点击那些轮播图片跳到product？id =20，

     他就会提示“”java.rmi.NoSuchObjectException: 访问的id不存在或已经被删除。  

    ”看了下源码，只有object == null)才会抛出此异常，看了下jdbc.properties文件也已经改为本地的数据库账号密码，请问是什么原因，为什么我的对象是空的呢？

**Comment by xenv** [comment]
我的代码没有使用 rmi 之类的包，这应该是 Tomcat 的问题或者是配置的问题，你可以试试 Tomcat8 或者重新配置一下 idea 。
rmi 是远程调用方法的协议。
还有问题的话，你可以贴出一下完整的报错堆栈信息。
