### ISSUE TITLE
用户注册验证用户名特殊符号错误

### ISSUE THREAD

**Issue by CleanWaterjx** [xenv/S-mall-ssm#9]
UserFrontController中23行
  if(!HtmlUtils.htmlEscape(name).equals(password)){
            msg = "用户名含有特殊字符，无法注册，请重新输入";
        }
应该是
  if(!HtmlUtils.htmlEscape(name).equals(name)){
            msg = "用户名含有特殊字符，无法注册，请重新输入";
        }
有个小建议这个验证可以在前端js验证
String.match( /^[\u4E00-\u9FA5a-zA-Z0-9]{1,}$/ )

**Comment by xenv** [comment]
https://github.com/xenv/S-mall-ssm/commit/c71d9446279b5a929e56d73f84eac6d4ed9facfd 修复了，前端验证你可以提个 pull request，我现在不维护这个项目了。
